version: "1.0"
services:
  mongoserver:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: houseoflife
      MONGO_INITDB_ROOT_PASSWORD: jki1NJ1l
    ports:
      - 1234:27017
    volumes:
      - /opt/oasis-jiwa/mongo-data:/data/db

  oasis-jiwa:
    build: .
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      MONGO_USERNAME: houseoflife
      MONGO_PASSWORD: jki1NJ1l
    volumes:
      - /opt/oasis-jiwa/app:/app